poets:
  - slug: Mutanabi
    name: المتنبي
    era: العصر العباسي
  - slug: abu-nawas
    name: ابو نواس
    era: العصر العباسي
  - slug: ahmed-shawqi
    name: أحمد شوقي
    era: العصر الحديث
  - slug: al-shafie
    name: الإمام الشافعي
    era: العصر العباسي
  - slug: al-asmaee
    name: الأصمعي
    era: العصر العباسي
  - slug: Mahmoud-Darwish
    name: محمود درويش
    era: العصر الحديث
  - slug: Antara-bin-Shaddad
    name: عنترة-بن-شداد
    era: العصر الجاهلي
  - slug: Imru-al-Qais
    name: امرؤ-القيس
    era: العصر الجاهلي
  - slug: Al-Farazdaq
    name: الفرزدق
    era: العصر الأموي
  - slug: Jarir
    name: جرير
    era: العصر الأموي
  - slug: abu-alatahyah
    name: أبو العتاهية
    era: العصر العباسي
  - slug: elia-abu-madi
    name: إيليا ابو ماضي
    era: العصر الحديث
